services:
  engine:
    build:
      context: ./backend/engine
      dockerfile: Dockerfile
    env_file:
      - ./backend/engine/.env
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./data:/app/data

  postgres:
    image: postgres:17.5-alpine
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - ./backend/engine/.env
    volumes:
      - ./backend/engine/postgres/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pg-data:/var/lib/postgresql/data

volumes:
  data:
  pg-data: